apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "join-apps.name" . }}-{{ .Values.names.dv }}
  labels:
    app: {{ template "join-apps.name" . }}-{{ .Values.names.dv }}
    chart: {{ template "join-apps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "join-apps.name" . }}-{{ .Values.names.dv }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "join-apps.name" . }}-{{ .Values.names.dv }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tagdv }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: WEB_PORT
            value: "{{ .Values.webport.dv }}"
          ports:
            - name: {{ .Values.webport.dvname }}
              containerPort: {{ .Values.webport.dv }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.webport.dvname }}
            initialDelaySeconds: {{ .Values.probes.init }}
            periodSeconds: {{ .Values.probes.period }}
            successThreshold: {{ .Values.probes.success }}
            failureThreshold: {{ .Values.probes.failure }}
            timeoutSeconds: {{ .Values.probes.timeout }}
          readinessProbe:
            httpGet:
              path: /dv
              port: {{ .Values.webport.dvname }}
            initialDelaySeconds: {{ .Values.probes.init }}
            periodSeconds: {{ .Values.probes.period }}
            successThreshold: {{ .Values.probes.success }}
            failureThreshold: {{ .Values.probes.failure }}
            timeoutSeconds: {{ .Values.probes.timeout }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "join-apps.name" . }}-{{ .Values.names.dv }}
  labels:
    app: {{ template "join-apps.name" . }}-{{ .Values.names.dv }}
    chart: {{ template "join-apps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.webport.dv }}
      targetPort: {{ .Values.webport.dv }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "join-apps.name" . }}-{{ .Values.names.dv }}
    release: {{ .Release.Name }}

